default:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      dbname: stock_ml
      port: 5432
      schema: public
      keepalives_idle: 0
      threads: 4
    duckdb:
      type: duckdb
      path: ../data/app.duckdb

